# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "taskmapper-basecamp"
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["HybridGroup"]
  s.date = "2012-04-20"
  s.description = "This gem provides an interface to basecamp through the taskmapper gem"
  s.email = "hong.quach@abigfisch.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".document",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/basecamp/basecamp.rb",
    "lib/provider/basecamp.rb",
    "lib/provider/comment.rb",
    "lib/provider/project.rb",
    "lib/provider/ticket.rb",
    "lib/taskmapper-basecamp.rb",
    "spec/comments_spec.rb",
    "spec/fixtures/comments.json",
    "spec/fixtures/comments.xml",
    "spec/fixtures/comments/74197051.json",
    "spec/fixtures/comments/74197051.xml",
    "spec/fixtures/comments/74197096.json",
    "spec/fixtures/comments/74197096.xml",
    "spec/fixtures/project_count.json",
    "spec/fixtures/project_count.xml",
    "spec/fixtures/projects.json",
    "spec/fixtures/projects.xml",
    "spec/fixtures/projects/5220065.json",
    "spec/fixtures/projects/5220065.xml",
    "spec/fixtures/projects/create.json",
    "spec/fixtures/projects/create.xml",
    "spec/fixtures/todo_items/62509330_todo_item.xml",
    "spec/fixtures/todo_list_9972756.xml",
    "spec/fixtures/todo_lists.json",
    "spec/fixtures/todo_lists.xml",
    "spec/fixtures/todo_lists/9972756_items.json",
    "spec/fixtures/todo_lists/9972756_items.xml",
    "spec/fixtures/todo_lists/9973518_items.json",
    "spec/fixtures/todo_lists/9973518_items.xml",
    "spec/fixtures/todo_lists/create.json",
    "spec/fixtures/todo_lists/create.xml",
    "spec/projects_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "spec/taskmapper-basecamp_spec.rb",
    "spec/tickets_spec.rb",
    "taskmapper-basecamp.gemspec"
  ]
  s.homepage = "http://github.com/kiafaldorius/taskmapper-basecamp"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.17"
  s.summary = "The basecamp provider for taskmapper"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<taskmapper>, ["~> 0.7.0"])
      s.add_runtime_dependency(%q<xml-simple>, ["~> 1.1"])
      s.add_development_dependency(%q<rspec>, ["~> 2.3"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6"])
      s.add_development_dependency(%q<simplecov>, ["~> 0.5"])
      s.add_development_dependency(%q<rcov>, ["~> 1.0"])
    else
      s.add_dependency(%q<taskmapper>, ["~> 0.7.0"])
      s.add_dependency(%q<xml-simple>, ["~> 1.1"])
      s.add_dependency(%q<rspec>, ["~> 2.3"])
      s.add_dependency(%q<jeweler>, ["~> 1.6"])
      s.add_dependency(%q<simplecov>, ["~> 0.5"])
      s.add_dependency(%q<rcov>, ["~> 1.0"])
    end
  else
    s.add_dependency(%q<taskmapper>, ["~> 0.7.0"])
    s.add_dependency(%q<xml-simple>, ["~> 1.1"])
    s.add_dependency(%q<rspec>, ["~> 2.3"])
    s.add_dependency(%q<jeweler>, ["~> 1.6"])
    s.add_dependency(%q<simplecov>, ["~> 0.5"])
    s.add_dependency(%q<rcov>, ["~> 1.0"])
  end
end

