# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ticketmaster-basecamp}
  s.version = "0.3.8"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["HybridGroup"]
  s.date = %q{2011-10-26}
  s.description = %q{This gem provides an interface to basecamp through the ticketmaster gem}
  s.email = %q{hong.quach@abigfisch.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/basecamp/basecamp.rb",
    "lib/provider/basecamp.rb",
    "lib/provider/comment.rb",
    "lib/provider/project.rb",
    "lib/provider/ticket.rb",
    "lib/ticketmaster-basecamp.rb",
    "spec/comments_spec.rb",
    "spec/fixtures/comments.json",
    "spec/fixtures/comments.xml",
    "spec/fixtures/comments/74197051.json",
    "spec/fixtures/comments/74197051.xml",
    "spec/fixtures/comments/74197096.json",
    "spec/fixtures/comments/74197096.xml",
    "spec/fixtures/project_count.json",
    "spec/fixtures/project_count.xml",
    "spec/fixtures/projects.json",
    "spec/fixtures/projects.xml",
    "spec/fixtures/projects/5220065.json",
    "spec/fixtures/projects/5220065.xml",
    "spec/fixtures/projects/create.json",
    "spec/fixtures/projects/create.xml",
    "spec/fixtures/todo_lists.json",
    "spec/fixtures/todo_lists.xml",
    "spec/fixtures/todo_lists/9972756_items.json",
    "spec/fixtures/todo_lists/9972756_items.xml",
    "spec/fixtures/todo_lists/9973518_items.json",
    "spec/fixtures/todo_lists/9973518_items.xml",
    "spec/projects_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "spec/ticketmaster-basecamp_spec.rb",
    "spec/tickets_spec.rb",
    "ticketmaster-basecamp.gemspec"
  ]
  s.homepage = %q{http://github.com/kiafaldorius/ticketmaster-basecamp}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.1}
  s.summary = %q{The basecamp provider for ticketmaster}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ticketmaster>, [">= 0.6.6"])
      s.add_runtime_dependency(%q<activesupport>, ["= 3.1.1"])
      s.add_runtime_dependency(%q<activeresource>, ["= 3.1.1"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<ticketmaster>, [">= 0.6.6"])
      s.add_dependency(%q<activesupport>, ["= 3.1.1"])
      s.add_dependency(%q<activeresource>, ["= 3.1.1"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<ticketmaster>, [">= 0.6.6"])
    s.add_dependency(%q<activesupport>, ["= 3.1.1"])
    s.add_dependency(%q<activeresource>, ["= 3.1.1"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

