# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ticketmaster-basecamp}
  s.version = "0.1.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["HybridGroup"]
  s.date = %q{2010-11-30}
  s.description = %q{This gem provides an interface to basecamp through the ticketmaster gem}
  s.email = %q{hong.quach@abigfisch.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "lib/basecamp/basecamp.rb",
     "lib/provider/basecamp.rb",
     "lib/provider/comment.rb",
     "lib/provider/project.rb",
     "lib/provider/ticket.rb",
     "lib/ticketmaster-basecamp.rb",
     "spec/comments_spec.rb",
     "spec/fixtures/comments.xml",
     "spec/fixtures/comments/74197051.xml",
     "spec/fixtures/comments/74197096.xml",
     "spec/fixtures/projects.xml",
     "spec/fixtures/projects/5220065.xml",
     "spec/fixtures/projects/create.xml",
     "spec/fixtures/todo_lists.xml",
     "spec/fixtures/todo_lists/9972756_items.xml",
     "spec/fixtures/todo_lists/9973518_items.xml",
     "spec/projects_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/ticketmaster-basecamp_spec.rb",
     "spec/tickets_spec.rb",
     "ticketmaster-basecamp.gemspec"
  ]
  s.homepage = %q{http://github.com/kiafaldorius/ticketmaster-basecamp}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{The basecamp provider for ticketmaster}
  s.test_files = [
    "spec/comments_spec.rb",
     "spec/projects_spec.rb",
     "spec/spec_helper.rb",
     "spec/ticketmaster-basecamp_spec.rb",
     "spec/tickets_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ticketmaster>, [">= 0.4.0"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<ticketmaster>, [">= 0.4.0"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<ticketmaster>, [">= 0.4.0"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

